name: 'Documentation Check'
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

permissions:
  contents: read

jobs:
  docs-required:
    name: 'Documentation Required'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Environment'
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: 'Clone repo'
        uses: actions/checkout@v4

      - name: Validate Docs
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          pip install requests --quiet
          python $GITHUB_WORKSPACE/.github/helper/documentation.py $PR_NUMBER
